"""add sent_at and send_method to quotations

Revision ID: 237c95070aa5
Revises: 1d368aaf2401
Create Date: 2025-08-25 16:15:08.161103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237c95070aa5'
down_revision = '1d368aaf2401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('send_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('send_method')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
