"""Adiciona name de volta em users

Revision ID: 697524300aa6
Revises: 28cd46628fe1
Create Date: 2025-09-08 22:26:08.805183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697524300aa6'
down_revision = '28cd46628fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
